version: '2'

services:
    postgres-service:
        image: postgres:latest
        ports:
            - "${DB_PORT}:5432"
        environment:
            - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
            - "PGDATA=${PGDATA}"
        volumes: 
            - /tmp/pgdata:/pgdata
    api:
        build: ./backend
        ports:
            - 80:80
        environment:
            - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
            - POSTGRES_SERVICE=postgres-service
            - "POSTGRES_PORT=${DB_PORT}"
            - "DB_NAME=${DB_NAME}"
        depends_on:
            - postgres-service
        volumes: 
            - /Users/martin/projects/fastapi_stock_screener/backend:/app
        command: /start-reload.sh